# fly.toml app configuration file generated for date-tv on 2024-01-07T09:47:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "date-tv"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
protocol = "tcp"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[[concurrency]]
hard_limit = 25
soft_limit = 20

[[ports]]
handlers = ["http"]
port = "80"

[[ports]]
handlers = ["tls", "http"]
port = "443"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
port = "8080"
restart_limit = 6
timeout = "2s"
